### ISSUE TITLE
doesn't save image

### ISSUE THREAD

**Issue by binaryfox0** [kbuffardi/Bitmap#2]
use bitmap using its but doesn't save image for new type

**Comment by kbuffardi** [comment]
@Octopus-Computer sorry for the long delay, I haven't been working on this repo in a while. Can you give me more specific details about what is happening? Or if you are requesting a specific feature, please elaborate on exactly what you want.

**Comment by binaryfox0** [comment]
hmm, my code it lost for corrupting ssd ,bruh
